name: Test
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ros-tooling/setup-ros-docker/setup-ros-docker-ubuntu-noble:master
    steps:
    - uses: ros-tooling/action-ros-ci@v0.4
      with:
        package-name: keyboard_handler
        target-ros2-distro: rolling
    - uses: actions/upload-artifact@v4
      with:
        name: colcon-logs
        path: ros_ws/log
